{% set version = "0.28.0" %}
package:
  name: rpds-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rpds-py/rpds_py-{{ version }}.tar.gz
  sha256: abd4df20485a0983e2ca334a216249b6186d6e3c1627e106651943dbdb791aea

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - python                                 # [build_platform != target_platform]
    - maturin >=1.9,<2.0                     # [build_platform != target_platform]
  host:
    - maturin >=1.9,<2.0
    - pip
    - python
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - rpds
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/crate-py/rpds
  summary: Python bindings to Rust's persistent data structures (rpds)
  description: Python bindings to Rust's persistent data structures (rpds)
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  dev_url: https://github.com/crate-py/rpds
  doc_url: https://github.com/crate-py/rpds?tab=readme-ov-file#usage

extra:
  recipe-maintainers:
    - bollwyvl
