{% set version = "0.10.3" %}

package:
  name: rpds-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rpds-py/rpds_py-{{ version }}.tar.gz
  sha256: fcc1ebb7561a3e24a6588f7c6ded15d80aec22c66a070c757559b57b17ffd1cb

build:
  number: 1
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.0,<2.0                     # [build_platform != target_platform]
  host:
    - maturin >=1.0,<2.0
    - pip
    - python
  run:
    - python

test:
  imports:
    - rpds
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/julian/rpds.py
  summary: Python bindings to Rust's persistent data structures (rpds)
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - bollwyvl
